# Generated by Django 2.2.1 on 2021-09-28 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autapi', '0003_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completeBy',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
