# Generated by Django 2.2.1 on 2021-09-28 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autapi', '0004_auto_20210928_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completeBy',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
